import string

ALLOWED_SHORT_CODE_CHARS = string.ascii_letters + string.digits
MAX_LENGTH_LINK = 2048
MAX_LENGTH_SHORT = 16
MAX_LENGTH_SHORT_AUTO = 6
MAX_ATTEMPTS_GENERATION_SHORT = 20
FORBIDDEN_SHORT_NAMES = {'files'}
REGEX_PATTERN_SHORT = f'^[{ALLOWED_SHORT_CODE_CHARS}]+$'
REDIRECT_VIEW_NAME = 'redirect_view'
