from string import ascii_letters, digits

ASCII_LETTERS_DIGITS = ascii_letters + digits
MAX_LENGTH_LINK = 2048
MAX_LENGTH_CUSTOM_SHORT = 16
MAX_LENGTH_RANDOM_SHORT = 6
MAX_ATTEMPTS_GENERATION_SHORT = 20
FORBIDDEN_SHORT_NAME = 'files'
REGEX_PATTERN_SHORT_NAME = r'^[a-zA-Z0-9]+$'
REDIRECT_VIEW_NAME = 'redirect_view'
