LETTERS_DIGITS = (
    'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
)
MAX_LENGTH_LINK = 2048
MAX_LENGTH_SHORT = 16
MAX_LENGTH_SHORT_AUTO = 6
MAX_ATTEMPTS_GENERATION_SHORT = 20
FORBIDDEN_SHORT_NAME = {'files'}
REGEX_PATTERN_SHORT = f'^[{LETTERS_DIGITS}]+$'
REDIRECT_VIEW_NAME = 'redirect_view'
